[workspace]
members = [
    "cli",
    "core",
    "gui/src-tauri"
]
resolver = "2"

[workspace.package]
version = "0.6.0"
edition = "2021"
authors = ["st4s1k"]
description = "Rust SSH automation tool"
license = "MIT OR Apache-2.0"
