[credentials]
username = "my_username" # will be added to the variables
password = "my_password" # if not provided, will use the ssh-agent
#                        # [!] the password will not be added to the variables

[server]
host = "localhost" # required
port = "22" # optional, default is 22

[execute]
steps = [
    { task = "copy_jar_to_server" },
    { task = "stop_service", on-fail = [
        "start_service"
    ] },
    { task = "create_backup", on-fail = [
        "start_service"
    ] },
    { task = "remove_current_deploy", on-fail = [
        "restore_backup",
        "start_service"
    ] },
    { task = "deploy_new_file", on-fail = [
        "restore_backup", 
        "start_service"
    ] },
    { task = "start_service", on-fail = [
        "restore_backup",
        "start_service" 
    ] }
]

# Required Variables

[variables.required]
local_jar_path = { type = "Path", label = "Local JAR Path" }
some_other_path = { type = "Path", label = "Some Other Path" }
some_variable = { type = "String", label = "Some Variable" }
timestamp = { type = "Timestamp", label = "Timestamp", format = "%Y-%m-%dT%H%M%S%:z", read_only = true }

# Defined Variables

[variables.defined]
service_name = "my_service"
remote_service_script_path = "/usr/local/bin/{service_name}.sh"
remote_deploy_path = "/usr/local/{service_name}/{service_name}.jar"
backup_path = "/u01/backup/{service_name}/{service_name}-{timestamp}.jar"
remote_base_path = "/home/{username}"

# Tasks
[tasks.copy_jar_to_server]
type = "SftpCopy"
description = "Copying new deploy file to server"
source_path = "{local_jar_path}"
destination_path = "{remote_base_path}/{basename:local_jar_path}"
error_message = "Failed to copy new deploy file to server."

[tasks.stop_service]
type = "RemoteSudo"
description = "Stopping the service on remote server"
command = "sudo {remote_service_script_path} stop"
error_message = "Failed to stop the service on the remote server."

[tasks.create_backup]
type = "RemoteSudo"
description = "Creating backup of current deployment"
command = "sudo cp -a {remote_deploy_path} {backup_path}"
error_message = "Failed to create backup of the current deployment."

[tasks.remove_current_deploy]
type = "RemoteSudo"
description = "Removing current deployment"
command = "sudo rm {remote_deploy_path} -f"
error_message = "Failed to remove the current deployment."

[tasks.deploy_new_file]
type = "RemoteSudo"
description = "Deploying the new file"
command = "sudo mv {remote_base_path}/{basename:local_jar_path} {remote_deploy_path}"
error_message = "Failed to deploy the new file."

[tasks.start_service]
type = "RemoteSudo"
description = "Starting the service on remote server"
command = "sudo {remote_service_script_path} start"
error_message = "Failed to start the service on the remote server."

[tasks.restore_backup]
type = "RemoteSudo"
description = "Restoring backup of current deployment"
command = "sudo cp -a {backup_path} {remote_deploy_path}"
error_message = "Failed to restore backup of the current deployment."
