parent = "./deploy-scenario.toml"

[credentials]
username = "my_username_service_two" # will be added to the variables
password = "my_password_service_two" # if not provided, will use the ssh-agent
#                                    # [!] the password will not be added to the variables

[server]
host = "service-two.example.com" # required
port = 24 # optional, default is 22

[variables.defined]
service_name = "service-two"
