[execute]
steps = [
    { task = "copy_jar_to_server" },
    { task = "stop_service", on-fail = [
        "start_service"
    ] },
    { task = "create_backup", on-fail = [
        "start_service"
    ] },
    { task = "remove_current_deploy", on-fail = [
        "restore_backup",
        "start_service"
    ] },
    { task = "deploy_new_file", on-fail = [
        "restore_backup",
        "start_service"
    ] },
    { task = "start_service", on-fail = [
        "restore_backup",
        "start_service"
    ] }
]

[variables.required]
"path:local_jar_path" = "Local JAR Path"
"remote_base_path" = "Remote Base Path"
"remote_service_script_path" = "Remote Service Script Path"
"remote_deploy_path" = "Remote Deploy Path"
"remote_backup_path" = "Remote Backup Path"

[tasks.copy_jar_to_server]
type = "SftpCopy"
description = "Copying new deploy file to server"
source_path = "{path:local_jar_path}"
destination_path = "{remote_base_path}/{basename:local_jar_path}"
error_message = "Failed to copy new deploy file to server."

[tasks.stop_service]
type = "RemoteSudo"
description = "Stopping the service on remote server"
command = "{remote_service_script_path} stop"
error_message = "Failed to stop the service on the remote server."

[tasks.create_backup]
type = "RemoteSudo"
description = "Creating backup of current deployment"
command = "cp -a {remote_deploy_path} {remote_backup_path}"
error_message = "Failed to create backup of the current deployment."

[tasks.remove_current_deploy]
type = "RemoteSudo"
description = "Removing current deployment"
command = "rm {remote_deploy_path}"
error_message = "Failed to remove the current deployment."

[tasks.deploy_new_file]
type = "RemoteSudo"
description = "Deploying the new file"
command = "mv {remote_base_path}/{basename:local_jar_path} {remote_deploy_path}"
error_message = "Failed to deploy the new file."

[tasks.start_service]
type = "RemoteSudo"
description = "Starting the service on remote server"
command = "{remote_service_script_path} start"
error_message = "Failed to start the service on the remote server."

[tasks.restore_backup]
type = "RemoteSudo"
description = "Restoring backup of current deployment"
command = "cp -a {remote_backup_path} {remote_deploy_path}"
error_message = "Failed to restore backup of the current deployment."
