schema = "../gen/schemas/desktop-schema.json"

identifier = "desktop-capability"
windows = ["main"]
platforms = ["linux", "macOS", "windows"]

permissions = [
  "core:default",
  "core:window:allow-toggle-maximize",
  "core:window:allow-minimize",
  "core:window:allow-close",
  "core:window:allow-start-dragging",
  "dialog:default",
  "shell:default",
  "shell:allow-open",
]
