[package]
name = "scenario-rs-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
thiserror = "2.0.18"
regex = "1.12.3"
ssh2 = "0.9.5"
serde = { version = "1.0.228", features = ["derive"] }
chrono = "0.4.44"
toml = "1.1.2+spec-1.1.0"
libc = "0.2"
tracing = { version = "0.1.44", features = ["attributes"] }
