[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.11"
regex = "1.11.1"
ssh2 = "0.9.5"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
chrono = "0.4.39"
toml = "0.8.20"
