[package]
name = "scenario-rs-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

[dependencies]
thiserror = "2.0.18"
regex = "1.12.3"
indexmap = { version = "2", features = ["serde"] }
schemars = { version = "1.2.1", features = ["indexmap2"] }
russh = { version = "0.60", default-features = false, features = ["ring"] }
russh-sftp = "2.1.1"
tokio = { version = "1", features = ["rt-multi-thread", "net"] }
serde = { version = "1.0.228", features = ["derive"] }
chrono = "0.4.44"
toml = "1.1.2"
tracing = { version = "0.1.44", features = ["attributes"] }

[dev-dependencies]
serde_json = "1"
tracing-subscriber = "0.3"
rand = "0.10.0"
tempfile = "3"
