identifier = "com.st4s1k.scenario-rs"

[build]
before-dev-command = "npm run start"
before-build-command = "npm run build"
dev-url = "http://localhost:1420"
frontend-dist = "../dist/gui/browser"

[[app.windows]]
decorations = false
title = "scenario-rs"

[bundle]
license = "MIT OR Apache-2.0"
active = true
targets = "all"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
