[build]
beforeDevCommand = "npm run start"
beforeBuildCommand = "npm run build"
devPath = "http://localhost:1420"
distDir = "../dist/gui/browser"

[package]
productName = "scenario-rs"
version = "0.1.0"

[tauri.allowlist]
all = false

[tauri.allowlist.shell]
all = false
open = true

[tauri.allowlist.dialog]
all = true
ask = true
confirm = true
message = true
open = true
save = true

[tauri.allowlist.window]
all = false
close = true
hide = true
show = true
maximize = true
minimize = true
unmaximize = true
unminimize = true
startDragging = true

[[tauri.windows]]
decorations = false
title = "scenario-rs"
width = 800
height = 600

[tauri.bundle]
active = true
targets = "all"
identifier = "com.st4s1k.scenario-rs.app"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]

custom-protocol = ["tauri/custom-protocol"]
